### ISSUE TITLE
requesting for update on the requirments

### ISSUE THREAD

**Issue by Falmi** [idiap/nnsslm#1]
Thanks for the recent updates to the source code. I have the following question.
1. you recommended python 2.7, but the apkit requires  python_requires='>=3.6' https://github.com/hwp/apkit/blob/master/setup.py#:~:text=python_requires%3D%27%3E%3D3.6%27%2C. how do you handle this?
2. PyTorch 0.2 is now very old is it okay if I use the recent version
3. Could you please provide the source for the raw dataset preprocessing?
Thanks,

**Comment by hwp** [comment]
Hi,

> you recommended python 2.7, but the apkit requires python_requires='>=3.6' https://github.com/hwp/apkit/blob/master/setup.py#:~:text=python_requires%3D%27%3E%3D3.6%27%2C. how do you handle this?

`nnsslm` is updated to support python 3. I recommend you to use python 3.8 and above. I will update the README.
 

> PyTorch 0.2 is now very old is it okay if I use the recent version

Our code should be compatible with PyTorch 0.2 and above. Using most recent version is recommended.

> Could you please provide the source for the raw dataset preprocessing?

Scripts to do data processing are provided in the SSLR dataset. I will update the README on how to use them.

**Comment by Falmi** [comment]
> Hi,
> 
> > you recommended python 2.7, but the apkit requires python_requires='>=3.6' https://github.com/hwp/apkit/blob/master/setup.py#:~:text=python_requires%3D%27%3E%3D3.6%27%2C. how do you handle this?
> 
> `nnsslm` is updated to support python 3. I recommend you to use python 3.8 and above. I will update the README.
> 
> > PyTorch 0.2 is now very old is it okay if I use the recent version
> 
> Our code should be compatible with PyTorch 0.2 and above. Using most recent version is recommended.
> 
> > Could you please provide the source for the raw dataset preprocessing?
> 
> Scripts to do data processing are provided in the SSLR dataset. I will update the README on how to use them.

Thanks
